/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	userSidebar: [{ type: 'autogenerated', dirName: '.' }],

	// mySidebar: [
	// 	{
	// 		type: 'category',
	// 		label: 'Getting Started',
	// 		items: ['started/intro', 'discussions/intro'],
	// 	},
	// 	{
	// 		type: 'category',
	// 		label: 'Groups',
	// 		items: ['groups/intro'],
	// 	},
	// ],

	// tutorialSidebar: {
	// 	'Getting started': ['started/intro'],
	// 	Groups: ['groups/intro'],
	// },

	// But you can create a sidebar manually

	// tutorialSidebar: [
	// 	{
	// 		type: 'category',
	// 		label: 'User Manual',
	// 		items: [
	// 			'started/intro',
	// 			'groups/intro',
	// 			'discussions/intro',
	// 			'meetings/intro',
	// 			'actions/intro',
	// 		],
	// 	},
	// ],
}
